
[platformio]
default_envs = nanoatmega328

;--------------------------------------------------------------------
; Quantum Retrum - Digital Clock
; 2026-03-14 - v1.0.0
;
; Platform: Arduino Nano (ATmega328P)
; Display: WeAct Studio TM1652 0.8 Digital Tube Module
; RTC: DS3231 Real Time Clock Module
; Light Sensor: TEMT6000 Ambient Light Sensor Module
;--------------------------------------------------------------------

[env:nanoatmega328]

platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 19200

lib_deps =
    adafruit/RTClib

;--------------------------------------------------------------------
;EOF